### ISSUE TITLE
Package Is Not Compatible With The Latest Version Of fastify.

### ISSUE THREAD

**Issue by Hamza-b93** [climba03003/fastify-formidable#199]
Hi.

fastify-formidable is not compatible with the latest version of fastify.

`FastifyError [Error]: fastify-plugin: fastify-formidable - expected '4.x' fastify version, '5.2.0' is installed`

Considering the package has not been updated in about 2 years, it seems an alternative will have to be used until the package is updated to work with the latest version of Fastify.

**Comment by climba03003** [comment]
Hi,

I have been moved all the multipart related plugins into a single package.
Github: https://github.com/kaka-ng/fastify-plugins/tree/main/packages/multipart
NPM: https://www.npmjs.com/package/@kakang/fastify-multipart

Most of the part is the same as before but provides customization on behavior.
